language: python
python:
    - '2.7'
    - '3.4'
    - 'pypy'
install:
  - 'pip install six'
  - 'pip install .'
  - 'pip install coverage'
  - 'pip install pytest-raisesregexp'
  - 'pip install coveralls'
  - 'pip install pytest'
script: 'coverage run --source . --omit setup.py -m py.test'
after_success: coveralls
